### ISSUE TITLE
Missing checkpoint / Access denied

### ISSUE THREAD

**Issue by raghavgoyal14** [TRI-ML/VOST#1]
Hi,

Thanks for sharing the wonderful work!
It seems like one of the link to the checkpoint is broken (access denied): https://tri-ml-public.s3.amazonaws.com/datasets/aotplus.pth
while the one pretrained on static and YouTubeVOS works (https://tri-ml-public.s3.amazonaws.com/datasets/pre_ytb.pth)

Thanks,
Raghav

**Comment by pvtokmakov** [comment]
Hi Raghav,

sorry about that. Should be fixed now.

**Comment by raghavgoyal14** [comment]
Thanks for the reply!
However, the issue still seems to persist. Here's the error message:

![image](https://user-images.githubusercontent.com/2176778/229558089-5c839323-043c-466c-8723-4e49efb2d5bb.png)

**Comment by pvtokmakov** [comment]
Sorry again, should definitely be fixed now :)

**Comment by raghavgoyal14** [comment]
It works now. Thank you so much!
